In [162]:
import pandas as pd
# Attempting to load the file with a different encoding
df = pd.read_excel('Suvidha_2.xlsx')

# Display the first few rows of the dataframe to understand its structure
df.head()

,Timestamp,Please enter your full name,Please write the Name of Newspaper - Newspaper Must be Indian English Newspaper listed above,Published date of News\nDate when the news article was published.,Headline of News Article\nHeadline / Title of the News Article from Source,"Content in detail of News article\nArticle in detail from data source (Make sure, data must be very clear)",Human Summary For Article (Use Bard/ChatGpt or Any other tool for summarization)\nWrite a summary of the article. Explain the news in your own words. Minimum 50 words and maximum 200 words,News Category (Please enter correctly)
0,NaN,NaN,The Assam Tribune,2022-05-27 00:00:00,Something weird is going on with our universe,Something weird is going on with how our unive...,NASA's Hubble Space Telescope has detected a s...,Science and Technology
1,NaN,NaN,The Assam Tribune,2022-05-27 00:00:00,The forbidden crop,"Ever since 1961, a popular crop suddenly becam...",Once popular but banned due to the neurotoxin ...,Health and Wellness
2,NaN,NaN,The Assam Tribune,2022-05-27 00:00:00,Right to Play,"While turning the pages of The Assam Tribune, ...",The article advocates for recognizing sports a...,Sports
3,NaN,NaN,The Assam Tribune,2022-05-27 00:00:00,Dealing With Bullying,"I don't want to go to school""... ""I don't want...",Children often express reluctance towards scho...,Human Interest
4,NaN,NaN,The Pioneer,2019-01-31 00:00:00,The final push,Will last-minute affirmative action and a veil...,The BJP seeks to regain momentum with last-min...,Politics

In [163]:
# List of newspapers to match
def match():
    newspapers = [
        "The Times of India", "The Hindu", "Hindustan Times", "Indian Express",
        "The Telegraph", "Deccan Chronicle", "The New Indian Express", "Mint",
        "Business Standard", "Financial Express", "DNA (Daily News and Analysis)",
        "The Tribune", "The Statesman", "The Asian Age", "The Pioneer", "The Free Press Journal",
        "The Economic Times", "The Mint", "The Afternoon Despatch & Courier", "The Sentinel",
        "The Navhind Times", "Goa Chronicle", "The Assam Tribune", "The Arunachal Times",
        "The Shillong Times", "The Imphal Free Press", "The Sikkim Express", "The Hans India",
        "The Orissa Post", "The Daily Post (Chandigarh)", "The Hitavada", "The Meghalaya Guardian",
        "The Morung Express", "The Sangai Express", "The Arunachal Front"
    ]
    
    # Check if entries in the third column are in the list of newspapers
    df['Is Newspaper Correct'] = df.iloc[:, 2].isin(newspapers)
    
    # Count the number of correct and incorrect matches
    correct_count = df['Is Newspaper Correct'].sum()
    incorrect_count = len(df) - correct_count
    
    return ('correct count:',correct_count), ('incorrect count:',incorrect_count)
match()

(('correct count:', 15816), ('incorrect count:', 5653))

In [164]:
# Filter the incorrect matches
def wrong_matches():
    incorrect_matches = df[~df['Is Newspaper Correct']]
    
    # Display the incorrect matches
    incorrect_matches_list = incorrect_matches.iloc[:, 2].unique()
    return incorrect_matches_list
wrong_matches()

array(['The Assam Tribune ', 'mint', 'The Economic TImes',
       'Time of india', 'Times of India ', 'Deccan Chronicle ',
       'Decan Chronicle', 'Deccan Chronicles', 'Times of India',
       'Times of time', 'Times of india', 'The hindu', 'Time of India ',
       'the hindu', 'the times of india ', 'The Indian Express',
       'the tribune', 'Economic times', 'The Times of India ',
       'The Hindu ', 'The times of india', 'Times Of India',
       'times of india', 'The Times Of India', 'Economic Times ', 'MInt',
       ' The Times of India', 'Hindustan TImes', 'Hindustan Times ',
       'HIndustan TImes', ' Times of india', 'The times of India',
       'The times of  India', 'Tye times of India', 'ECONOMIC TIMES',
       'ECONOMIC TIMES ', 'Hidustan Times', 'The Hans India ',
       'The Navhind Times ', 'Business Standard ', 'The Time of India',
       'the times of india', 'THE ECONOMIC TIMES', 'Times of Indian',
       'the hindu ', 'Times of IndIa', 'ECOMNOMIC TIMES',
       'Times of  India', 'The times of india ', 'The Pioneer ',
       'The  Times of India', 'HIndustan Times', 'The Tines of India',
       'THE TIMES OF INDIA ', 'THE TIMES OF INDIA', 'THE HINDU', 'Mint ',
       'ECONOMIC  TIMES', 'ECCONOMIC TIMES', 'The Times of india',
       'The Times of  India', 'The Times of India The Hindu',
       'HINDUSTAN TIMES', 'ECONOMICN TIMES ', 'The Times if India',
       'The Time Of India', 'HINDUSTAN  TIMES', 'TOI', 'ECONOMIC',
       'ECONNOMIC TIMES ', ' The Hindu', 'the Hindu', 'The hINdu',
       'The Times Of Insidia',
       'The Times of India                                                                                                                                                                                                 text&utm_campaign=cppst              ',
       'time sof india', 'HINDUSTAN TIMES ', 'the hundu',
       'Indian express', 'The Economic Times ', 'The Economics Times',
       'The EConomics Times', 'Economics Times', 'INDIAN EXPRESS',
       'Econmics Times', 'ECOONOMIC TIMES', 'ECONOMIC TIIMES',
       'The Econmics Times', 'The Ecnomics Times', 'Goa Chronicle ',
       'the Economics Times', 'The Economics Times ',
       'The Ecoomies Times', 'The Economies Times ',
       'The Economies Times', 'The Economics Time', 'The Econ0mics Times',
       'The Ecnmics Times', ' THE TIMES OF INDIA', 'THE TTIMES OF INDIA',
       'THE TIMES OF  INDIA', 'TIMES OF INDIA', 'indian express',
       'The economic times', 'Thd economic times ', 'the economic times',
       'DECCAN CHRONICLE', 'THE NEW INDIAN EXPRESS', 'The Indian times',
       'The hindu ', 'THE TIMES OFF INDIA', 'THE TIMES OFINDIA',
       'THE TIMES OG INDIA', 'THE TIMES OF INIDA', 'THE TIME SOF INDIA',
       'THE TIMES OD INDIA', ' TIMES OF INDIA', 'THE ECCNOMIC TIMES',
       'THETIMES OF INDIA', 'THE TIMES 0F INDIA', 'THE TIMES OF HINDHU',
       'RHE TIMES OF INDIA', 'THE TIME OF INDIA', 'Indian express ',
       ' Hindustan Times', ' Financial Express', ' Indian Express',
       ' The New Indian Express', 'THE ECOMONOMICS TIMES', ' Mint',
       'he Times of India', ': Hindustan Times', 'the telegraph',
       ': The Telegraph', 'Economic Times', 'India Today',
       'the new India express ', 'hindustan times', 'The hitavada',
       'The Times Of India ', 'THE TIMES OF INFDIA',
       'The Business Standard', 'The Business Interest', 'miint', ' mint',
       'The economic Times ', 'The HIndu', ' The Telegraph',
       'Financial Epress', 'Financial express', 'financial Epress', 'DNA',
       'Financial express ', ' the tribune', ' Business Standard',
       'Th Mint', 'The Orissa Post ', 'THE HINDU ',
       ' The Imphal Free Press', 'Hindustan times',
       'The  Times Of India ', 'the statesman ', 'the statesman',
       'The Business Standerd', 'The BusinessStanderd', 'The Trinune',
       'The Shillong Times ', 'The Business Business',
       'The Arunachal Times ', ' The Free Press Journal',
       ' The Economic Times', 'The Busienss Standerd', 'Hindusthan Times',
       'Hindustan Times News', 'Indian Express ', ' Indian Express ',
       'The Hiindu', 'India Express', 'The hindus', 'The Telegraph ',
       'the Arunachal Times', 'The Hidu', 'Time of India', 'The Hindi',
       'Time Of India', 'Times OF India', 'The Hidnu', 'time of india',
       'times of india ', 'The Trubune', 'Business Standards',
       'THe Tribune', 'The tribune', 'Financial Exress',
       'Financial Exxpress', 'The telegraph', 'The Telagraph',
       'The Time of india', 'The Economic times', 'Finanacial Express',
       'Times  of india', 'times od india', 'THe Pioneer', 'DNA ',
       'The pioneer', 'The Pionner', ' The Indian Express',
       'the Times of India', 'The statesman', 'The Statesmsn',
       'Then Statesman', 'the Statesman', 'The arunachal front ',
       'The arunachal  front ', 'The Arunachal front ',
       'The arunachal front', 'The  sangai express ',
       'The  sangai express', 'The sangai express ',
       'The sangai  express ', 'The Morung Express ', 'THE ECONOIC TIMES',
       'THE ARUNACHAL FRONT', 'THe Statesman', 'Times odf India',
       'The Salesman', 'The Gurdian', 'The Daily Post', 'India News',
       'The telegraph ', 'The economics time', 'The financial express',
       'The Arunachal Frone', 'The TImes of India', 'The Indian Experss',
       'The Telegrpah', 'The Times ofI ndia', 'The Tribune ',
       'The Financial Express', '.The Hindu',
       ' The Afternoon Despatch & Courier', 'The Sikkim Express ',
       'Indian Expres', 'The Tmes of India', 'The Hindustan Times',
       'The mint', 'The economics Times', 'The sangai Express',
       'THe Times of India', 'The Hindu Business Line',
       ' The Indain Express', 'The Statesmen', 'The pioneer ',
       'The Arunachal TImes', 'The Ties of India', 'The time of India ',
       'Business standard', 'Business Category', ' INDIAN EXPRESS',
       'thr tribune', 'the tirbune', 'The tirbune', 'Times of Inida',
       'THe tribune', ' The Navhind Times',
       ' The Daily Post (Chandigarh)', 'Financia Express',
       'Financial Expresss', 'DNA India', 'the mint',
       "The time's of India ", 'the arunachal times',
       'The ARunachal  Times', ' The Arunachal Times',
       'The ARunachal Times', '    The Arunachal Times',
       'he Arunachal Times', '  The Arunachal Times',
       'The Arunachal Pradesh', 'India express ', ' The Mint',
       ' The Asian Age', 'The Statemans', ' The Pioneer',
       'Finantial Express', 'The Statesaman', 'the Arunachal Pradesh',
       'The New Indian Express ', 'The Sikkim Express  ',
       'THE TOMES OF INDIA', 'THE TIMES  OF INDIA', 'THE ARUNACHAL TIMES',
       'The Arunachal times', 'The Arunachal times ', 'THE HINDHU',
       'The Times of Inadia', 'The3 Hindu', 'Times of india ', 'the hind',
       'The arunachal time ', 'The arunachal time', 'Sikkim Express',
       'SikkimExpress', 'Deccan Herald', 'the Times of India ',
       'The Time of india ', ' The Arunachal Front', 'The Arunachl Times',
       'times oof india', 'tribune', 'trribune', 'The Mint ',
       'ThePioneer', 'the pioneer', 'tribbune', 'the arunachal pradesh ',
       'The Arunachal Movie', 'The Times of India  ', 'The Daily Times',
       'Business Daily', 'The Daily Times\t', 'The Evening Gazette',
       'TIMES OF INDIA ', 'pioneer', ' The Tribune',
       'The Arunachal  Times', 'Imphal Free Press', 'The ArunachalTimes',
       'The indian express', 'finanicial express', 'finanacial express',
       'financial express', 'finaciql express', 'The aTimes of India',
       'The times of India ', 'India Today  ', 'Deccan Chronicle  ',
       'he Hans India '], dtype=object)

In [165]:
# Get the row numbers with incorrect matches
#incorrect_row_numbers = incorrect_matches.index.tolist()
incorrect_row_numbers = [x + 2 for x in incorrect_matches.index.tolist()]

# Display the row numbers
print(incorrect_row_numbers)

[2, 3, 4, 5, 39, 40, 41, 42, 43, 44, 45, 48, 52, 55, 56, 57, 58, 59, 63, 64, 70, 71, 74, 75, 76, 121, 142, 173, 184, 186, 210, 211, 212, 213, 214, 243, 244, 245, 246, 247, 248, 250, 270, 282, 299, 301, 304, 305, 306, 307, 316, 321, 323, 326, 327, 329, 330, 331, 332, 333, 335, 336, 338, 342, 343, 344, 345, 349, 350, 360, 361, 363, 379, 383, 387, 390, 393, 395, 398, 402, 405, 430, 434, 443, 445, 446, 447, 448, 449, 450, 451, 454, 455, 457, 459, 461, 462, 463, 464, 466, 467, 468, 470, 471, 472, 474, 475, 478, 482, 485, 487, 489, 490, 493, 496, 498, 499, 500, 502, 503, 507, 512, 545, 550, 552, 553, 554, 555, 557, 558, 561, 562, 567, 570, 574, 575, 578, 580, 583, 585, 586, 588, 590, 592, 593, 597, 598, 600, 602, 604, 607, 608, 610, 613, 615, 616, 617, 618, 621, 623, 625, 626, 628, 630, 635, 636, 637, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 685, 686, 687, 690, 691, 693, 696, 700, 744, 747, 749, 750, 751, 752, 765, 794, 801, 804, 807, 809, 812, 820, 825, 829, 831, 834, 835, 837, 838, 841, 842, 844, 849, 852, 856, 858, 863, 865, 868, 870, 872, 888, 890, 893, 894, 949, 954, 957, 958, 960, 961, 962, 963, 964, 965, 966, 968, 972, 983, 986, 987, 989, 991, 997, 1003, 1009, 1026, 1029, 1032, 1035, 1037, 1040, 1041, 1044, 1060, 1061, 1062, 1071, 1102, 1104, 1107, 1109, 1110, 1111, 1114, 1115, 1116, 1117, 1119, 1120, 1122, 1124, 1126, 1127, 1130, 1132, 1134, 1136, 1138, 1146, 1148, 1150, 1152, 1154, 1155, 1161, 1164, 1165, 1168, 1172, 1174, 1175, 1177, 1179, 1180, 1182, 1183, 1185, 1187, 1188, 1191, 1192, 1194, 1195, 1196, 1198, 1199, 1201, 1203, 1204, 1205, 1207, 1208, 1209, 1211, 1212, 1213, 1215, 1217, 1218, 1220, 1222, 1225, 1228, 1229, 1230, 1231, 1233, 1234, 1235, 1236, 1237, 1238, 1239, 1240, 1241, 1242, 1243, 1244, 1250, 1252, 1255, 1256, 1259, 1260, 1262, 1264, 1265, 1267, 1268, 1270, 1272, 1273, 1274, 1276, 1277, 1280, 1281, 1283, 1284, 1285, 1286, 1289, 1291, 1312, 1316, 1317, 1319, 1320, 1322, 1354, 1356, 1359, 1361, 1378, 1380, 1381, 1383, 1385, 1388, 1392, 1395, 1398, 1400, 1402, 1403, 1404, 1405, 1406, 1408, 1409, 1410, 1412, 1413, 1415, 1418, 1420, 1422, 1424, 1425, 1427, 1429, 1430, 1432, 1433, 1442, 1445, 1448, 1450, 1452, 1453, 1454, 1455, 1457, 1459, 1460, 1461, 1462, 1464, 1465, 1466, 1468, 1470, 1472, 1473, 1475, 1476, 1477, 1479, 1480, 1481, 1482, 1483, 1486, 1487, 1488, 1489, 1490, 1491, 1493, 1494, 1495, 1496, 1498, 1499, 1501, 1502, 1504, 1505, 1510, 1514, 1516, 1520, 1521, 1522, 1524, 1527, 1529, 1530, 1532, 1533, 1534, 1535, 1537, 1539, 1540, 1543, 1545, 1546, 1549, 1550, 1552, 1557, 1559, 1561, 1564, 1565, 1566, 1567, 1568, 1569, 1570, 1571, 1572, 1573, 1574, 1575, 1577, 1578, 1579, 1581, 1582, 1583, 1585, 1586, 1587, 1590, 1591, 1592, 1593, 1594, 1598, 1600, 1603, 1607, 1608, 1650, 1651, 1652, 1653, 1654, 1655, 1657, 1659, 1661, 1663, 1664, 1665, 1666, 1667, 1668, 1670, 1671, 1673, 1674, 1677, 1678, 1679, 1681, 1682, 1686, 1687, 1689, 1692, 1693, 1696, 1698, 1700, 1703, 1706, 1709, 1711, 1712, 1721, 1722, 1724, 1725, 1727, 1728, 1729, 1730, 1733, 1737, 1740, 1741, 1742, 1744, 1746, 1747, 1751, 1752, 1755, 1759, 1765, 1767, 1769, 1771, 1772, 1773, 1775, 1784, 1785, 1786, 1787, 1789, 1790, 1792, 1793, 1794, 1795, 1796, 1798, 1800, 1802, 1807, 1809, 1810, 1812, 1813, 1814, 1815, 1818, 1823, 1824, 1825, 1828, 1831, 1833, 1838, 1839, 1842, 1844, 1847, 1852, 1859, 1862, 1869, 1879, 1885, 1887, 1889, 1911, 1912, 1913, 1917, 1918, 1919, 1921, 1924, 1926, 1930, 1932, 1939, 1942, 1947, 1948, 1951, 1956, 1966, 1991, 1992, 1994, 1995, 2000, 2007, 2014, 2019, 2022, 2024, 2025, 2026, 2030, 2031, 2032, 2034, 2037, 2039, 2041, 2043, 2046, 2047, 2050, 2052, 2054, 2055, 2057, 2062, 2066, 2067, 2069, 2072, 2075, 2077, 2081, 2084, 2087, 2089, 2093, 2094, 2096, 2097, 2098, 2102, 2105, 2107, 2110, 2111, 2114, 2117, 2128, 2131, 2132, 2136, 2139, 2143, 2146, 2148, 2149, 2150, 2154, 2155, 2156, 2157, 2183, 2184, 2188, 2198, 2212, 2214, 2217, 2218, 2221, 2223, 2225, 2227, 2228, 2230, 2231, 2236, 2238, 2239, 2241, 2243, 2247, 2249, 2251, 2253, 2256, 2260, 2261, 2262, 2264, 2265, 2267, 2269, 2270, 2271, 2273, 2275, 2276, 2278, 2280, 2281, 2284, 2287, 2289, 2290, 2291, 2292, 2293, 2295, 2296, 2299, 2301, 2304, 2305, 2308, 2311, 2314, 2315, 2316, 2317, 2318, 2320, 2321, 2322, 2330, 2334, 2339, 2353, 2357, 2362, 2364, 2376, 2380, 2387, 2406, 2411, 2412, 2414, 2415, 2417, 2418, 2419, 2420, 2421, 2423, 2424, 2425, 2427, 2428, 2429, 2431, 2432, 2433, 2443, 2444, 2445, 2446, 2447, 2448, 2449, 2451, 2452, 2453, 2454, 2455, 2456, 2457, 2458, 2459, 2460, 2461, 2462, 2463, 2464, 2465, 2467, 2468, 2469, 2470, 2471, 2472, 2473, 2474, 2475, 2476, 2477, 2478, 2479, 2480, 2482, 2483, 2484, 2485, 2486, 2487, 2488, 2490, 2491, 2492, 2493, 2494, 2495, 2496, 2497, 2498, 2499, 2500, 2501, 2502, 2503, 2504, 2505, 2506, 2507, 2508, 2509, 2510, 2511, 2512, 2513, 2514, 2515, 2516, 2517, 2518, 2519, 2520, 2521, 2522, 2523, 2524, 2525, 2526, 2527, 2528, 2529, 2530, 2531, 2532, 2533, 2534, 2535, 2536, 2537, 2538, 2539, 2540, 2541, 2542, 2543, 2544, 2545, 2546, 2547, 2554, 2568, 2571, 2572, 2573, 2574, 2575, 2576, 2577, 2578, 2579, 2580, 2581, 2582, 2583, 2584, 2585, 2586, 2587, 2588, 2589, 2590, 2591, 2593, 2595, 2597, 2598, 2615, 2627, 2629, 2687, 2692, 2715, 2725, 2727, 2729, 2730, 2731, 2732, 2733, 2734, 2735, 2736, 2738, 2740, 2741, 2742, 2744, 2749, 2750, 2752, 2753, 2754, 2755, 2756, 2758, 2759, 2760, 2762, 2764, 2765, 2767, 2769, 2771, 2772, 2775, 2777, 2783, 2787, 2789, 2790, 2791, 2793, 2795, 2797, 2799, 2801, 2802, 2804, 2805, 2807, 2808, 2809, 2810, 2812, 2813, 2814, 2816, 2817, 2820, 2823, 2824, 2825, 2827, 2828, 2829, 2830, 2832, 2833, 2834, 2835, 2837, 2838, 2840, 2841, 2843, 2853, 2933, 2943, 2957, 2959, 2960, 2964, 2965, 2968, 2970, 2972, 2974, 2975, 2976, 2978, 2980, 2981, 2983, 2985, 2986, 2988, 2989, 2990, 2991, 2992, 2993, 2995, 2996, 2998, 2999, 3000, 3001, 3002, 3003, 3004, 3005, 3006, 3007, 3008, 3009, 3010, 3011, 3012, 3013, 3014, 3015, 3016, 3017, 3018, 3019, 3020, 3021, 3022, 3023, 3024, 3025, 3026, 3027, 3028, 3029, 3030, 3031, 3032, 3033, 3034, 3035, 3036, 3037, 3038, 3039, 3040, 3041, 3042, 3043, 3044, 3045, 3046, 3047, 3048, 3049, 3050, 3051, 3052, 3053, 3054, 3055, 3056, 3057, 3058, 3059, 3060, 3061, 3062, 3063, 3064, 3065, 3066, 3067, 3068, 3069, 3070, 3071, 3072, 3073, 3074, 3075, 3076, 3077, 3161, 3162, 3163, 3164, 3165, 3166, 3167, 3168, 3169, 3170, 3171, 3172, 3173, 3174, 3175, 3176, 3177, 3178, 3179, 3180, 3181, 3182, 3183, 3184, 3185, 3186, 3187, 3188, 3189, 3190, 3191, 3192, 3193, 3194, 3195, 3196, 3197, 3198, 3199, 3200, 3202, 3203, 3204, 3205, 3206, 3207, 3208, 3209, 3210, 3211, 3212, 3213, 3214, 3215, 3216, 3217, 3218, 3219, 3220, 3221, 3222, 3223, 3224, 3225, 3226, 3227, 3228, 3229, 3230, 3231, 3232, 3233, 3234, 3235, 3236, 3237, 3238, 3239, 3240, 3242, 3243, 3245, 3250, 3254, 3256, 3257, 3258, 3259, 3260, 3261, 3262, 3263, 3264, 3265, 3266, 3267, 3268, 3269, 3270, 3271, 3272, 3274, 3275, 3276, 3278, 3280, 3282, 3283, 3284, 3286, 3318, 3319, 3321, 3322, 3324, 3325, 3327, 3328, 3329, 3330, 3331, 3332, 3333, 3334, 3335, 3336, 3337, 3338, 3339, 3340, 3342, 3343, 3346, 3350, 3352, 3354, 3356, 3357, 3360, 3363, 3364, 3366, 3368, 3371, 3373, 3375, 3377, 3380, 3383, 3386, 3404, 3406, 3407, 3410, 3411, 3412, 3414, 3416, 3418, 3420, 3423, 3425, 3427, 3429, 3430, 3431, 3433, 3437, 3439, 3441, 3443, 3444, 3445, 3446, 3447, 3448, 3449, 3450, 3451, 3452, 3453, 3454, 3481, 3482, 3483, 3484, 3485, 3486, 3487, 3488, 3489, 3490, 3491, 3492, 3493, 3494, 3495, 3496, 3497, 3498, 3499, 3500, 3501, 3502, 3503, 3504, 3505, 3506, 3507, 3508, 3509, 3510, 3511, 3512, 3513, 3514, 3515, 3516, 3517, 3518, 3519, 3520, 3521, 3522, 3523, 3524, 3525, 3526, 3527, 3528, 3529, 3530, 3531, 3532, 3533, 3534, 3535, 3536, 3537, 3538, 3539, 3540, 3541, 3542, 3543, 3544, 3545, 3546, 3550, 3551, 3552, 3553, 3554, 3555, 3556, 3557, 3558, 3559, 3560, 3566, 3568, 3569, 3570, 3572, 3573, 3574, 3575, 3576, 3577, 3578, 3579, 3580, 3581, 3585, 3586, 3587, 3589, 3592, 3594, 3595, 3597, 3598, 3600, 3601, 3603, 3605, 3606, 3607, 3608, 3609, 3610, 3611, 3612, 3613, 3614, 3615, 3616, 3617, 3618, 3619, 3620, 3621, 3622, 3623, 3624, 3625, 3626, 3627, 3628, 3629, 3630, 3632, 3633, 3634, 3635, 3636, 3644, 3650, 3651, 3652, 3656, 3657, 3660, 3661, 3663, 3664, 3671, 3673, 3675, 3677, 3679, 3681, 3682, 3685, 3686, 3688, 3690, 3691, 3693, 3694, 3696, 3698, 3700, 3703, 3704, 3705, 3710, 3712, 3714, 3715, 3716, 3717, 3718, 3720, 3721, 3722, 3723, 3725, 3726, 3727, 3728, 3729, 3730, 3731, 3732, 3733, 3734, 3735, 3736, 3738, 3739, 3740, 3741, 3743, 3744, 3745, 3746, 3747, 3748, 3749, 3750, 3752, 3753, 3754, 3755, 3756, 3757, 3759, 3760, 3761, 3762, 3763, 3764, 3765, 3766, 3767, 3768, 3769, 3770, 3771, 3772, 3773, 3774, 3775, 3776, 3778, 3779, 3781, 3783, 3785, 3786, 3788, 3789, 3791, 3793, 3794, 3796, 3799, 3800, 3802, 3803, 3804, 3806, 3808, 3809, 3810, 3811, 3812, 3813, 3814, 3815, 3817, 3818, 3819, 3821, 3822, 3826, 3827, 3829, 3830, 3831, 3833, 3834, 3836, 3837, 3839, 3840, 3841, 3843, 3844, 3846, 3847, 3848, 3849, 3850, 3852, 3853, 3855, 3856, 3857, 3859, 3860, 3861, 3863, 3864, 3865, 3866, 3867, 3868, 3869, 3870, 3871, 3873, 3874, 3876, 3878, 3879, 3880, 3881, 3882, 3883, 3885, 3887, 3888, 3889, 3890, 3891, 3892, 3893, 3895, 3896, 3897, 3898, 3899, 3901, 3902, 3903, 3904, 3905, 3907, 3909, 3911, 3912, 3915, 3918, 3919, 3921, 3923, 3926, 3928, 3930, 3934, 3936, 3937, 3939, 3940, 3942, 3944, 3946, 3948, 4033, 4036, 4037, 4038, 4040, 4043, 4044, 4045, 4046, 4047, 4048, 4049, 4050, 4051, 4053, 4054, 4055, 4056, 4057, 4058, 4059, 4060, 4061, 4062, 4063, 4064, 4065, 4066, 4067, 4068, 4069, 4070, 4071, 4072, 4073, 4074, 4075, 4077, 4079, 4081, 4084, 4085, 4086, 4087, 4088, 4089, 4090, 4091, 4092, 4093, 4094, 4095, 4096, 4097, 4098, 4099, 4100, 4101, 4102, 4103, 4104, 4105, 4106, 4107, 4108, 4109, 4110, 4111, 4237, 4238, 4239, 4240, 4241, 4242, 4243, 4244, 4245, 4246, 4247, 4248, 4249, 4250, 4251, 4252, 4253, 4254, 4255, 4256, 4257, 4258, 4259, 4260, 4261, 4262, 4263, 4264, 4265, 4266, 4267, 4268, 4269, 4271, 4272, 4274, 4276, 4278, 4280, 4281, 4283, 4285, 4287, 4288, 4290, 4291, 4305, 4306, 4307, 4308, 4309, 4310, 4311, 4312, 4313, 4314, 4315, 4316, 4317, 4318, 4319, 4320, 4321, 4322, 4323, 4324, 4325, 4326, 4327, 4328, 4329, 4330, 4331, 4332, 4333, 4334, 4335, 4336, 4337, 4338, 4339, 4340, 4341, 4342, 4344, 4345, 4346, 4347, 4349, 4350, 4351, 4352, 4353, 4354, 4355, 4356, 4357, 4358, 4359, 4360, 4361, 4362, 4363, 4364, 4365, 4366, 4367, 4368, 4369, 4370, 4371, 4372, 4373, 4374, 4375, 4376, 4377, 4378, 4379, 4380, 4381, 4382, 4383, 4384, 4385, 4386, 4387, 4388, 4389, 4390, 4391, 4393, 4394, 4395, 4396, 4397, 4398, 4399, 4400, 4401, 4402, 4403, 4404, 4405, 4406, 4407, 4408, 4409, 4410, 4411, 4412, 4413, 4414, 4415, 4416, 4417, 4418, 4419, 4420, 4421, 4422, 4423, 4424, 4425, 4426, 4427, 4428, 4429, 4430, 4431, 4432, 4433, 4434, 4435, 4436, 4437, 4438, 4439, 4440, 4441, 4442, 4443, 4444, 4445, 4446, 4447, 4448, 4449, 4450, 4451, 4452, 4453, 4455, 4457, 4458, 4460, 4461, 4462, 4463, 4464, 4465, 4467, 4468, 4469, 4470, 4471, 4472, 4473, 4474, 4475, 4476, 4477, 4478, 4479, 4480, 4481, 4482, 4484, 4485, 4486, 4488, 4489, 4490, 4491, 4492, 4494, 4495, 4496, 4498, 4499, 4500, 4501, 4503, 4504, 4505, 4506, 4508, 4509, 4510, 4512, 4513, 4514, 4515, 4516, 4517, 4518, 4520, 4521, 4522, 4523, 4524, 4525, 4526, 4527, 4528, 4529, 4530, 4531, 4532, 4533, 4534, 4535, 4536, 4537, 4538, 4540, 4541, 4543, 4545, 4546, 4547, 4548, 4549, 4550, 4551, 4552, 4553, 4554, 4555, 4556, 4557, 4558, 4559, 4560, 4561, 4562, 4563, 4564, 4566, 4567, 4570, 4571, 4573, 4574, 4575, 4578, 4579, 4582, 4583, 4584, 4586, 4588, 4589, 4591, 4592, 4593, 4595, 4596, 4599, 4600, 4602, 4603, 4604, 4606, 4607, 4609, 4614, 4618, 4624, 4625, 4626, 4627, 4628, 4629, 4630, 4631, 4632, 4633, 4634, 4635, 4636, 4637, 4682, 4684, 4687, 4688, 4694, 4697, 4702, 4704, 4708, 4709, 4713, 4714, 4718, 4722, 4724, 4725, 4726, 4727, 4731, 4734, 4737, 4738, 4740, 4741, 4742, 4743, 4747, 4752, 4754, 4756, 4757, 4760, 4762, 4764, 4768, 4769, 4770, 4772, 4776, 4778, 4784, 4785, 4787, 4788, 4791, 4792, 4797, 4798, 4801, 4804, 4807, 4809, 4812, 4815, 4818, 4821, 4824, 4827, 4828, 4831, 4841, 4850, 4866, 4869, 4874, 4878, 4882, 4888, 4890, 4894, 4896, 4901, 4905, 4909, 4910, 4911, 4912, 4915, 4919, 4922, 4923, 4924, 4926, 4936, 4942, 4943, 4944, 4945, 4946, 4947, 4948, 4949, 4950, 4951, 4952, 4953, 4954, 4955, 4956, 4957, 4958, 4964, 4965, 4966, 4967, 4968, 4969, 4970, 4971, 4972, 4973, 4974, 4975, 4976, 4977, 4978, 4979, 4980, 4981, 4982, 4983, 4984, 4985, 4986, 4987, 4988, 4989, 4990, 4991, 4992, 4993, 4994, 4995, 4996, 4997, 4998, 4999, 5000, 5003, 5014, 5021, 5028, 5082, 5100, 5103, 5108, 5115, 5122, 5123, 5126, 5128, 5130, 5131, 5132, 5134, 5135, 5136, 5138, 5139, 5141, 5143, 5145, 5146, 5147, 5149, 5151, 5152, 5154, 5155, 5157, 5158, 5159, 5160, 5162, 5164, 5165, 5167, 5168, 5188, 5197, 5199, 5200, 5202, 5204, 5206, 5210, 5212, 5214, 5215, 5217, 5219, 5220, 5222, 5224, 5226, 5231, 5234, 5238, 5242, 5245, 5248, 5253, 5258, 5261, 5265, 5269, 5273, 5279, 5281, 5286, 5290, 5296, 5299, 5302, 5305, 5342, 5346, 5358, 5388, 5390, 5393, 5395, 5396, 5399, 5400, 5403, 5405, 5406, 5425, 5433, 5434, 5442, 5443, 5444, 5445, 5446, 5447, 5448, 5449, 5450, 5451, 5452, 5453, 5454, 5455, 5456, 5457, 5458, 5460, 5461, 5464, 5465, 5467, 5468, 5469, 5470, 5472, 5473, 5474, 5475, 5478, 5480, 5481, 5482, 5484, 5485, 5487, 5488, 5489, 5491, 5492, 5493, 5494, 5495, 5496, 5497, 5498, 5499, 5500, 5501, 5502, 5503, 5504, 5507, 5511, 5512, 5517, 5519, 5520, 5522, 5523, 5525, 5526, 5527, 5528, 5529, 5530, 5532, 5533, 5534, 5535, 5537, 5538, 5539, 5541, 5542, 5543, 5544, 5546, 5547, 5549, 5552, 5554, 5555, 5556, 5557, 5561, 5563, 5574, 5577, 5580, 5583, 5632, 5636, 5645, 5663, 5686, 5692, 5709, 5710, 5711, 5712, 5713, 5714, 5715, 5716, 5717, 5718, 5719, 5720, 5721, 5722, 5723, 5724, 5725, 5726, 5727, 5728, 5729, 5730, 5731, 5732, 5733, 5734, 5735, 5736, 5737, 5738, 5740, 5741, 5743, 5744, 5745, 5747, 5748, 5750, 5751, 5752, 5753, 5754, 5755, 5756, 5757, 5758, 5759, 5760, 5761, 5762, 5763, 5764, 5765, 5766, 5767, 5771, 5772, 5774, 5775, 5777, 5778, 5782, 5788, 5789, 5791, 5792, 5793, 5795, 5796, 5797, 5798, 5799, 5800, 5801, 5802, 5803, 5804, 5805, 5807, 5808, 5810, 5811, 5812, 5813, 5814, 5815, 5816, 5819, 5820, 5821, 5822, 5823, 5824, 5826, 5827, 5828, 5829, 5830, 5831, 5832, 5833, 5834, 5835, 5836, 5837, 5838, 5839, 5841, 5842, 5843, 5844, 5846, 5847, 5848, 5849, 5851, 5852, 5853, 5854, 5855, 5857, 5858, 5859, 5860, 5861, 5862, 5863, 5865, 5866, 5867, 5868, 5869, 5871, 5872, 5873, 5874, 5875, 5877, 5878, 5879, 5880, 5882, 5883, 5885, 5887, 5889, 5890, 5906, 5909, 5912, 5915, 5917, 5921, 5923, 5927, 5929, 5931, 5934, 5939, 5952, 5955, 5975, 5976, 5981, 5998, 6006, 6008, 6011, 6013, 6015, 6016, 6017, 6019, 6020, 6023, 6026, 6028, 6029, 6031, 6033, 6037, 6039, 6040, 6043, 6046, 6048, 6050, 6051, 6053, 6054, 6055, 6056, 6057, 6058, 6060, 6061, 6062, 6063, 6064, 6065, 6066, 6067, 6068, 6069, 6070, 6071, 6074, 6076, 6079, 6080, 6082, 6085, 6086, 6089, 6138, 6144, 6187, 6242, 6244, 6245, 6246, 6248, 6250, 6251, 6252, 6253, 6255, 6279, 6311, 6324, 6340, 6350, 6357, 6358, 6361, 6362, 6364, 6366, 6369, 6371, 6372, 6374, 6375, 6378, 6379, 6380, 6381, 6383, 6385, 6387, 6389, 6391, 6396, 6397, 6400, 6404, 6411, 6414, 6415, 6418, 6419, 6422, 6424, 6426, 6429, 6431, 6434, 6435, 6439, 6444, 6451, 6454, 6457, 6459, 6460, 6461, 6466, 6471, 6474, 6477, 6480, 6482, 6515, 6535, 6536, 6538, 6540, 6541, 6542, 6543, 6544, 6545, 6546, 6547, 6548, 6549, 6577, 6579, 6581, 6584, 6587, 6590, 6592, 6597, 6599, 6601, 6603, 6604, 6606, 6608, 6611, 6613, 6616, 6619, 6620, 6622, 6626, 6627, 6630, 6631, 6635, 6636, 6637, 6639, 6640, 6643, 6644, 6648, 6651, 6655, 6657, 6664, 6669, 6677, 6678, 6684, 6694, 6701, 6728, 6759, 6768, 6772, 6773, 6774, 6775, 6777, 6779, 6781, 6809, 6843, 6847, 6850, 6852, 6857, 6862, 6867, 6869, 6874, 6878, 6881, 6887, 6893, 6896, 6903, 6904, 6907, 6909, 6911, 6919, 6921, 6924, 6927, 6930, 6932, 6934, 6937, 6939, 6942, 7035, 7036, 7037, 7087, 7097, 7111, 7126, 7135, 7140, 7150, 7154, 7157, 7158, 7162, 7165, 7167, 7169, 7172, 7174, 7178, 7180, 7183, 7185, 7189, 7191, 7196, 7200, 7203, 7206, 7208, 7209, 7216, 7219, 7226, 7230, 7236, 7251, 7261, 7279, 7283, 7291, 7304, 7306, 7310, 7311, 7313, 7315, 7316, 7319, 7321, 7323, 7325, 7326, 7328, 7330, 7331, 7334, 7335, 7339, 7340, 7342, 7345, 7346, 7349, 7351, 7353, 7356, 7357, 7361, 7363, 7367, 7368, 7383, 7433, 7457, 7471, 7477, 7478, 7481, 7483, 7486, 7492, 7498, 7516, 7530, 7539, 7540, 7541, 7542, 7543, 7545, 7547, 7550, 7551, 7552, 7554, 7555, 7557, 7558, 7560, 7561, 7562, 7563, 7564, 7565, 7566, 7567, 7569, 7571, 7572, 7573, 7575, 7576, 7577, 7578, 7580, 7581, 7582, 7585, 7586, 7587, 7594, 7609, 7615, 7623, 7634, 7639, 7641, 7642, 7645, 7646, 7666, 7673, 7679, 7692, 7696, 7699, 7705, 7710, 7711, 7712, 7713, 7714, 7715, 7717, 7718, 7719, 7720, 7721, 7722, 7726, 7727, 7728, 7730, 7731, 7732, 7734, 7738, 7740, 7744, 7747, 7772, 7776, 7816, 7838, 7841, 7888, 8185, 8191, 8887, 8890, 8892, 8900, 8911, 8915, 8919, 8921, 8924, 8926, 8933, 8934, 8939, 8941, 8942, 8943, 8945, 8946, 8948, 8949, 8951, 8994, 8996, 8998, 9000, 9013, 9018, 9020, 9029, 9034, 9040, 9041, 9042, 9045, 9048, 9092, 9093, 9134, 9135, 9136, 9139, 9141, 9145, 9148, 9149, 9150, 9151, 9158, 9165, 9170, 9175, 9180, 9181, 9200, 9212, 9214, 9218, 9221, 9222, 9224, 9228, 9230, 9233, 9234, 9236, 9243, 9247, 9270, 9272, 9275, 9278, 9286, 9287, 9300, 9303, 9304, 9309, 9313, 9314, 9316, 9318, 9329, 9332, 9340, 9343, 9344, 9354, 9359, 9361, 9362, 9412, 9418, 9422, 9428, 9431, 9432, 9434, 9435, 9437, 9440, 9441, 9442, 9443, 9444, 9445, 9450, 9509, 9511, 9515, 9517, 9519, 9522, 9523, 9525, 9526, 9527, 9529, 9531, 9533, 9534, 9547, 9556, 9560, 9571, 9578, 9579, 9593, 9595, 9597, 9599, 9600, 9602, 9604, 9606, 9608, 9610, 9612, 9614, 9616, 9617, 9619, 9621, 9622, 9624, 9625, 9627, 9630, 9633, 9636, 9639, 9642, 9644, 9647, 9669, 9682, 9693, 9704, 9705, 9707, 9708, 9709, 9710, 9711, 9712, 9713, 9714, 9715, 9716, 9717, 9718, 9719, 9720, 9721, 9722, 9723, 9724, 9725, 9726, 9727, 9728, 9729, 9730, 9731, 9732, 9733, 9734, 9736, 9738, 9741, 9781, 9786, 9815, 9829, 9835, 9842, 9851, 9858, 9879, 9890, 9918, 9920, 9979, 10026, 10033, 10036, 10038, 10041, 10042, 10046, 10052, 10058, 10063, 10066, 10069, 10074, 10078, 10080, 10084, 10087, 10088, 10090, 10093, 10094, 10095, 10096, 10097, 10098, 10099, 10101, 10102, 10103, 10104, 10105, 10106, 10108, 10109, 10110, 10111, 10112, 10113, 10114, 10115, 10116, 10117, 10121, 10122, 10123, 10124, 10125, 10126, 10131, 10132, 10133, 10134, 10136, 10137, 10170, 10188, 10192, 10196, 10199, 10201, 10204, 10205, 10209, 10210, 10212, 10215, 10226, 10241, 10243, 10248, 10251, 10255, 10277, 10288, 10294, 10306, 10320, 10332, 10334, 10336, 10342, 10345, 10348, 10366, 10371, 10374, 10385, 10387, 10391, 10395, 10397, 10400, 10405, 10406, 10407, 10409, 10411, 10412, 10414, 10418, 10421, 10422, 10423, 10426, 10428, 10432, 10434, 10459, 10462, 10465, 10467, 10476, 10477, 10479, 10489, 10516, 10527, 10531, 10535, 10544, 10555, 10557, 10577, 10583, 10588, 10611, 10613, 10614, 10615, 10616, 10619, 10621, 10623, 10624, 10626, 10628, 10629, 10631, 10632, 10635, 10636, 10638, 10639, 10641, 10644, 10647, 10652, 10653, 10658, 10660, 10662, 10664, 10665, 10669, 10673, 10677, 10679, 10681, 10685, 10686, 10688, 10691, 10696, 10700, 10703, 10708, 10709, 10710, 10712, 10714, 10715, 10717, 10719, 10721, 10725, 10729, 10731, 10733, 10734, 10735, 10737, 10738, 10739, 10740, 10741, 10742, 10744, 10745, 10746, 10748, 10750, 10752, 10754, 10756, 10772, 10806, 10819, 10820, 10821, 10824, 10833, 10837, 10846, 10847, 10853, 10857, 10861, 10867, 10870, 10871, 10874, 10875, 10876, 10877, 10882, 10883, 10885, 10888, 10890, 10891, 10893, 10896, 10898, 10899, 10902, 10903, 10905, 10907, 10912, 10913, 10915, 10917, 10921, 10922, 10923, 10925, 10927, 10930, 10935, 10937, 10938, 10940, 1

In [166]:
# Count the number of leading and trailing spaces in the third column
def lead_trail_space():
    df['Leading Spaces'] = df.iloc[:, 2].str.len() - df.iloc[:, 2].str.lstrip().str.len()
    df['Trailing Spaces'] = df.iloc[:, 2].str.len() - df.iloc[:, 2].str.rstrip().str.len()
    
    # Summing up the leading and trailing spaces
    total_leading_spaces = df['Leading Spaces'].sum()
    total_trailing_spaces = df['Trailing Spaces'].sum()
    
    return ("Total leading spaces:", total_leading_spaces),("Total trailing spaces:", total_trailing_spaces),('leading+trailing spaces', total_leading_spaces+total_trailing_spaces)
lead_trail_space()

(('Total leading spaces:', 481),
 ('Total trailing spaces:', 1242),
 ('leading+trailing spaces', 1723))

In [167]:
# Remove leading and trailing spaces in the third column
df.iloc[:, 2] = df.iloc[:, 2].str.strip()
lead_trail_space()

(('Total leading spaces:', 0),
 ('Total trailing spaces:', 0),
 ('leading+trailing spaces', 0))

In [168]:
# List of newspapers to match
match()

(('correct count:', 17208), ('incorrect count:', 4261))

In [169]:
wrong_matches()

array(['mint', 'The Economic TImes', 'Time of india', 'Times of India',
       'Decan Chronicle', 'Deccan Chronicles', 'Times of time',
       'Times of india', 'The hindu', 'Time of India', 'the hindu',
       'the times of india', 'The Indian Express', 'the tribune',
       'Economic times', 'The times of india', 'Times Of India',
       'times of india', 'The Times Of India', 'Economic Times', 'MInt',
       'Hindustan TImes', 'HIndustan TImes', 'The times of India',
       'The times of  India', 'Tye times of India', 'ECONOMIC TIMES',
       'Hidustan Times', 'The Time of India', 'THE ECONOMIC TIMES',
       'Times of Indian', 'Times of IndIa', 'ECOMNOMIC TIMES',
       'Times of  India', 'The  Times of India', 'HIndustan Times',
       'The Tines of India', 'THE TIMES OF INDIA', 'THE HINDU',
       'ECONOMIC  TIMES', 'ECCONOMIC TIMES', 'The Times of india',
       'The Times of  India', 'The Times of India The Hindu',
       'HINDUSTAN TIMES', 'ECONOMICN TIMES', 'The Times if India',
       'The Time Of India', 'HINDUSTAN  TIMES', 'TOI', 'ECONOMIC',
       'ECONNOMIC TIMES', 'the Hindu', 'The hINdu',
       'The Times Of Insidia',
       'The Times of India                                                                                                                                                                                                 text&utm_campaign=cppst',
       'time sof india', 'the hundu', 'Indian express',
       'The Economics Times', 'The EConomics Times', 'Economics Times',
       'INDIAN EXPRESS', 'Econmics Times', 'ECOONOMIC TIMES',
       'ECONOMIC TIIMES', 'The Econmics Times', 'The Ecnomics Times',
       'the Economics Times', 'The Ecoomies Times', 'The Economies Times',
       'The Economics Time', 'The Econ0mics Times', 'The Ecnmics Times',
       'THE TTIMES OF INDIA', 'THE TIMES OF  INDIA', 'TIMES OF INDIA',
       'indian express', 'The economic times', 'Thd economic times',
       'the economic times', 'DECCAN CHRONICLE', 'THE NEW INDIAN EXPRESS',
       'The Indian times', 'THE TIMES OFF INDIA', 'THE TIMES OFINDIA',
       'THE TIMES OG INDIA', 'THE TIMES OF INIDA', 'THE TIME SOF INDIA',
       'THE TIMES OD INDIA', 'THE ECCNOMIC TIMES', 'THETIMES OF INDIA',
       'THE TIMES 0F INDIA', 'THE TIMES OF HINDHU', 'RHE TIMES OF INDIA',
       'THE TIME OF INDIA', 'THE ECOMONOMICS TIMES', 'he Times of India',
       ': Hindustan Times', 'the telegraph', ': The Telegraph',
       'India Today', 'the new India express', 'hindustan times',
       'The hitavada', 'THE TIMES OF INFDIA', 'The Business Standard',
       'The Business Interest', 'miint', 'The economic Times',
       'The HIndu', 'Financial Epress', 'Financial express',
       'financial Epress', 'DNA', 'Th Mint', 'Hindustan times',
       'The  Times Of India', 'the statesman', 'The Business Standerd',
       'The BusinessStanderd', 'The Trinune', 'The Business Business',
       'The Busienss Standerd', 'Hindusthan Times',
       'Hindustan Times News', 'The Hiindu', 'India Express',
       'The hindus', 'the Arunachal Times', 'The Hidu', 'The Hindi',
       'Time Of India', 'Times OF India', 'The Hidnu', 'time of india',
       'The Trubune', 'Business Standards', 'THe Tribune', 'The tribune',
       'Financial Exress', 'Financial Exxpress', 'The telegraph',
       'The Telagraph', 'The Time of india', 'The Economic times',
       'Finanacial Express', 'Times  of india', 'times od india',
       'THe Pioneer', 'The pioneer', 'The Pionner', 'the Times of India',
       'The statesman', 'The Statesmsn', 'Then Statesman',
       'the Statesman', 'The arunachal front', 'The arunachal  front',
       'The Arunachal front', 'The  sangai express', 'The sangai express',
       'The sangai  express', 'THE ECONOIC TIMES', 'THE ARUNACHAL FRONT',
       'THe Statesman', 'Times odf India', 'The Salesman', 'The Gurdian',
       'The Daily Post', 'India News', 'The economics time',
       'The financial express', 'The Arunachal Frone',
       'The TImes of India', 'The Indian Experss', 'The Telegrpah',
       'The Times ofI ndia', 'The Financial Express', '.The Hindu',
       'Indian Expres', 'The Tmes of India', 'The Hindustan Times',
       'The mint', 'The economics Times', 'The sangai Express',
       'THe Times of India', 'The Hindu Business Line',
       'The Indain Express', 'The Statesmen', 'The Arunachal TImes',
       'The Ties of India', 'The time of India', 'Business standard',
       'Business Category', 'thr tribune', 'the tirbune', 'The tirbune',
       'Times of Inida', 'THe tribune', 'Financia Express',
       'Financial Expresss', 'DNA India', 'the mint',
       "The time's of India", 'the arunachal times',
       'The ARunachal  Times', 'The ARunachal Times',
       'he Arunachal Times', 'The Arunachal Pradesh', 'India express',
       'The Statemans', 'Finantial Express', 'The Statesaman',
       'the Arunachal Pradesh', 'THE TOMES OF INDIA',
       'THE TIMES  OF INDIA', 'THE ARUNACHAL TIMES',
       'The Arunachal times', 'THE HINDHU', 'The Times of Inadia',
       'The3 Hindu', 'the hind', 'The arunachal time', 'Sikkim Express',
       'SikkimExpress', 'Deccan Herald', 'The Arunachl Times',
       'times oof india', 'tribune', 'trribune', 'ThePioneer',
       'the pioneer', 'tribbune', 'the arunachal pradesh',
       'The Arunachal Movie', 'The Daily Times', 'Business Daily',
       'The Evening Gazette', 'pioneer', 'The Arunachal  Times',
       'Imphal Free Press', 'The ArunachalTimes', 'The indian express',
       'finanicial express', 'finanacial express', 'financial express',
       'finaciql express', 'The aTimes of India', 'he Hans India'],
      dtype=object)

In [170]:
from fuzzywuzzy import fuzz
# Function to correct values using fuzzy matching
def correct_value(value, correct_values):
    closest_match, score = process.extractOne(value, correct_values)
    return closest_match

# Correcting values in column 3
for i in range(len(df)):
    df.iloc[i, 2] = correct_value(df.iloc[i, 2], newspapers)

In [171]:
match()

(('correct count:', 21469), ('incorrect count:', 0))

In [172]:
df.head()

,Timestamp,Please enter your full name,Please write the Name of Newspaper - Newspaper Must be Indian English Newspaper listed above,Published date of News\nDate when the news article was published.,Headline of News Article\nHeadline / Title of the News Article from Source,"Content in detail of News article\nArticle in detail from data source (Make sure, data must be very clear)",Human Summary For Article (Use Bard/ChatGpt or Any other tool for summarization)\nWrite a summary of the article. Explain the news in your own words. Minimum 50 words and maximum 200 words,News Category (Please enter correctly),Is Newspaper Correct,Leading Spaces,Trailing Spaces
0,NaN,NaN,The Assam Tribune,2022-05-27 00:00:00,Something weird is going on with our universe,Something weird is going on with how our unive...,NASA's Hubble Space Telescope has detected a s...,Science and Technology,True,0,0
1,NaN,NaN,The Assam Tribune,2022-05-27 00:00:00,The forbidden crop,"Ever since 1961, a popular crop suddenly becam...",Once popular but banned due to the neurotoxin ...,Health and Wellness,True,0,0
2,NaN,NaN,The Assam Tribune,2022-05-27 00:00:00,Right to Play,"While turning the pages of The Assam Tribune, ...",The article advocates for recognizing sports a...,Sports,True,0,0
3,NaN,NaN,The Assam Tribune,2022-05-27 00:00:00,Dealing With Bullying,"I don't want to go to school""... ""I don't want...",Children often express reluctance towards scho...,Human Interest,True,0,0
4,NaN,NaN,The Pioneer,2019-01-31 00:00:00,The final push,Will last-minute affirmative action and a veil...,The BJP seeks to regain momentum with last-min...,Politics,True,0,0

In [175]:
df = df.iloc[:, [*range(8), *range(11, len(df.columns))]]
df.head()

,Timestamp,Please enter your full name,Please write the Name of Newspaper - Newspaper Must be Indian English Newspaper listed above,Published date of News\nDate when the news article was published.,Headline of News Article\nHeadline / Title of the News Article from Source,"Content in detail of News article\nArticle in detail from data source (Make sure, data must be very clear)",Human Summary For Article (Use Bard/ChatGpt or Any other tool for summarization)\nWrite a summary of the article. Explain the news in your own words. Minimum 50 words and maximum 200 words,News Category (Please enter correctly)
0,NaN,NaN,The Assam Tribune,2022-05-27 00:00:00,Something weird is going on with our universe,Something weird is going on with how our unive...,NASA's Hubble Space Telescope has detected a s...,Science and Technology
1,NaN,NaN,The Assam Tribune,2022-05-27 00:00:00,The forbidden crop,"Ever since 1961, a popular crop suddenly becam...",Once popular but banned due to the neurotoxin ...,Health and Wellness
2,NaN,NaN,The Assam Tribune,2022-05-27 00:00:00,Right to Play,"While turning the pages of The Assam Tribune, ...",The article advocates for recognizing sports a...,Sports
3,NaN,NaN,The Assam Tribune,2022-05-27 00:00:00,Dealing With Bullying,"I don't want to go to school""... ""I don't want...",Children often express reluctance towards scho...,Human Interest
4,NaN,NaN,The Pioneer,2019-01-31 00:00:00,The final push,Will last-minute affirmative action and a veil...,The BJP seeks to regain momentum with last-min...,Politics

In [176]:
df.to_excel('output.xlsx', index=False)